import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import Box from '@mui/material/Box';
import Navigation from './components/Navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback="false">
          <Navigation />
        </Suspense>
        <Box
          sx={{
            m: 1,
            p: 1,
            border: '2px solid rgba(0, 0, 0, 0.12)',
            borderRadius: 2
          }}
        >
          {children}
        </Box>
      </body>
    </html>
  );
}
